# Generated by Django 5.1.15 on 2026-09-29 03:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the facility category (e.g., Computer Laboratory, Auditorium).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional summary of what this category encompasses.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this facility type was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this facility type was last updated.')),
            ],
            options={
                'verbose_name': 'Facility Type',
                'verbose_name_plural': 'Facility Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique facility name or room identifier (e.g., IT ComLab 1, DSSC Gymnasium).', max_length=150, unique=True)),
                ('location', models.CharField(help_text='Physical campus location (e.g., Admin Building 2nd Floor, Main Campus Ground).', max_length=200)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum seating or occupant capacity. Must be at least 1.', validators=[django.core.validators.MinValueValidator(1, message='Capacity must be at least 1 person.')])),
                ('description', models.TextField(blank=True, default='', help_text='Details on amenities, equipment, projectors, or special usage policies.')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', help_text='Current physical operational status (AVAILABLE, UNAVAILABLE, MAINTENANCE).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this facility was registered.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this facility details were last updated.')),
                ('facility_type', models.ForeignKey(help_text='Category of this facility. Protected from deletion if facilities exist.', on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.facilitytype')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='facility_capacity_gt_zero')],
            },
        ),
    ]
