# Generated by Django 5.1.15 on 2026-09-30 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of the maintenance work (e.g. "Annual electrical inspection").', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Optional details about the maintenance scope, technicians, or notes.')),
                ('maintenance_date', models.DateField(help_text='Date on which the maintenance window occurs.')),
                ('start_time', models.TimeField(help_text='Start time of the maintenance window.')),
                ('end_time', models.TimeField(help_text='End time of the maintenance window (must be later than start time).')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', help_text='Current lifecycle status of this maintenance record.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this maintenance record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this maintenance record was last updated.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff or Admin who scheduled this maintenance. Retained as null if the user account is later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(help_text='Facility this maintenance window applies to. PROTECT: a facility cannot be deleted while maintenance records exist.', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'Facility Maintenance',
                'verbose_name_plural': 'Facility Maintenance Records',
                'ordering': ['-maintenance_date', '-start_time'],
                'indexes': [models.Index(fields=['facility', 'maintenance_date', 'status'], name='maint_fac_date_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='maintenance_end_after_start')],
            },
        ),
    ]
