# Generated by Django 5.1.15 on 2026-09-29 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text='Stated objective or event for this reservation.', max_length=255)),
                ('reservation_date', models.DateField(help_text='Date when the facility is to be used.')),
                ('start_time', models.TimeField(help_text='Start time of the reservation.')),
                ('end_time', models.TimeField(help_text='End time of the reservation (must be later than start time).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current reservation lifecycle status.', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the reservation was approved or rejected.', null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Explanation provided by staff/admin if rejected.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the reservation request was submitted.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified.')),
                ('facility', models.ForeignKey(help_text='Facility being requested.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facilities.facility')),
                ('requested_by', models.ForeignKey(help_text='User who submitted the reservation request.', on_delete=django.db.models.deletion.CASCADE, related_name='requested_reservations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff or Admin who approved or rejected this reservation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-reservation_date', '-start_time'],
                'indexes': [models.Index(fields=['facility', 'reservation_date', 'status'], name='res_fac_date_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='reservation_end_after_start')],
            },
        ),
    ]
