# Generated by Django 5.1.15 on 2026-10-05 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The human-readable notification text shown to the recipient.')),
                ('is_read', models.BooleanField(default=False, help_text='False until the recipient explicitly reads this notification.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this notification was created.')),
                ('recipient', models.ForeignKey(help_text='The user who receives and owns this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, help_text='The reservation this notification relates to. SET_NULL preserves notification history if the reservation is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recip_read_ts_idx')],
            },
        ),
    ]
